
-- CUSTOMER TABLE
CREATE TABLE CUSTOMER (
    CUSTOMERID CHAR(5) PRIMARY KEY,
    FNAME VARCHAR(15) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    PHONE CHAR(12) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) CHECK (STATUS IN ('PLATINUM', 'GOLD', 'SILVER', 'REGULAR')),
    CREDIT_LINE DECIMAL(10,2),
    HOME_ADDR CHAR(5) NOT NULL,
    UNIQUE (CUSTOMERID),
    FOREIGN KEY (HOME_ADDR) REFERENCES LOCATIONS(LOCATIONID)
);

-- LOCATIONS TABLE
CREATE TABLE LOCATIONS (
    LOCATIONID CHAR(5) PRIMARY KEY,
    APTNO INTEGER,
    STREET VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    ZIP_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(30) NOT NULL,
    GIVEN_NAME VARCHAR(30),
    OWNER_ID CHAR(5),
    IS_HOME_ADDRESS BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (OWNER_ID) REFERENCES CUSTOMER(CUSTOMERID)
);

-- CREDIT CARD TABLE
CREATE TABLE CREDIT_CARD (
    CARD_NUMBER VARCHAR(20) PRIMARY KEY,
    SECNUMBER VARCHAR(4) NOT NULL,
    OWNER_NAME VARCHAR(20) NOT NULL,
    OID CHAR(5) NOT NULL,
    CARD_TYPE VARCHAR(15),
    BILL_ADDRESS VARCHAR(320),
    EXPRY_DATE DATE,
    FOREIGN KEY (OID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE
);

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCTID CHAR(5) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30),
    QUANTITY INTEGER NOT NULL DEFAULT 0,
    PRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PTYPE VARCHAR(15) NOT NULL,
    DESCRIPTION TEXT DEFAULT 'Default Product'
);

-- COMPUTER TABLE
CREATE TABLE COMPUTER (
    PID CHAR(4) PRIMARY KEY,
    CPUTYPE VARCHAR(10),
    FOREIGN KEY (PID) REFERENCES PRODUCTS(PRODUCTID)
);

-- PRINTER TABLE
CREATE TABLE PRINTER (
    PID CHAR(4) PRIMARY KEY,
    PRINTER_TYPE VARCHAR(25),
    RESOLUTION VARCHAR(9),
    FOREIGN KEY (PID) REFERENCES PRODUCTS(PRODUCTID)
);

-- LAPTOP TABLE
CREATE TABLE LAPTOP (
    PID CHAR(4) PRIMARY KEY,
    BATTERY_TIME VARCHAR(10),
    WEIGHT DECIMAL(3,2),
    FOREIGN KEY (PID) REFERENCES PRODUCTS(PRODUCTID)
);

-- CART TABLE
CREATE TABLE CART (
    CARTID CHAR(5) PRIMARY KEY,
    TOTAL DECIMAL(10,2),
    CID CHAR(5) NOT NULL,
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CUSTOMERID) ON DELETE CASCADE
);

-- CART_ENTRY TABLE
CREATE TABLE CART_ENTRY (
    CARTID CHAR(5),
    PID CHAR(4),
    QUANTITY INTEGER NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (CARTID, PID),
    FOREIGN KEY (CARTID) REFERENCES CART(CARTID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE  
);

/*CREATE TRIGGER offer_price 
ON CART_ENTRY
FOR EACH ROW
AFTER INSERT 
BEGIN
IF CARTID IN (SELECT CARTID FROM CART WHERE CID IN (SELECT CUSTOMERID    FROM CUSTOMER WHERE STATUS IN   (‘GOLD’,’PLATINUM’) ) 
)
	AND
PID IN (SELECT PID FROM OFFER)

SET PRICE = (SELECT PRICE FROM OFFER O WHERE O.PID = PID);
END--*/


-- OFFER TABLE
CREATE TABLE OFFER (
    PID CHAR(5) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (PID, PRICE),
    FOREIGN KEY (PID) REFERENCES PRODUCTS(PRODUCTID)
)

-- TRANSACTION TABLE
CREATE TABLE TRANSACTIONS (
    TRANSACTIONID SERIAL PRIMARY KEY,
    CARTID CHAR(5) NOT NULL,
    CID CHAR(5) NOT NULL,
    SAName VARCHAR(20) NOT NULL,
    TDATE DATE,
    CCNUMBER VARCHAR(20) NOT NULL,
    TTAG VARCHAR(20),
    TOTAL DECIMAL(10,2),
    FOREIGN KEY (CARTID) REFERENCES CART(CARTID),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CUSTOMERID),
    FOREIGN KEY (CCNUMBER) REFERENCES CREDIT_CARD(CARD_NUMBER)
);

-- ORDERS TABLE
CREATE TABLE ORDERS (
    TID INTEGER NOT NULL,
    CID CHAR(5) NOT NULL,
    STATUS VARCHAR(50),
    SHIPPING_ADDRESS CHAR(5) NOT NULL,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    FOREIGN KEY (TID) REFERENCES TRANSACTIONS(TRANSACTIONID),
    FOREIGN KEY (CID) REFERENCES CUSTOMER(CUSTOMERID)
);








-- Sample LOCATIONS
INSERT INTO LOCATIONS (LOCATIONID, APTNO, STREET, CITY, STATE, ZIP_CODE, COUNTRY, GIVEN_NAME, OWNER_ID, IS_HOME_ADDRESS)
VALUES ('L001', 101, '123 Main St', 'New York', 'NY', '10001', 'USA', 'Home', NULL, TRUE);

-- Sample CUSTOMER
INSERT INTO CUSTOMER (CUSTOMERID, FNAME, LNAME, PHONE, EMAIL, STATUS, CREDIT_LINE, HOME_ADDR)
VALUES ('C001', 'Alice', 'Smith', '123456789012', 'alice@example.com', 'GOLD', 5000.00, 'L001');

-- Sample CREDIT_CARD
INSERT INTO CREDIT_CARD (CARD_NUMBER, SECNUMBER, OWNER_NAME, OID, CARD_TYPE, BILL_ADDRESS, EXPRY_DATE)
VALUES ('4111111111111111', '123', 'Alice Smith', 'C001', 'VISA', '123 Main St, New York, NY 10001', '2026-12-31');

-- Sample PRODUCTS
INSERT INTO PRODUCTS (PRODUCTID, PRODUCT_NAME, QUANTITY, PRICE, PTYPE, DESCRIPTION)
VALUES ('P001', 'Gaming Laptop', 10, 1500.00, 'LAPTOP', 'High-performance gaming laptop');

-- Sample COMPUTER
INSERT INTO COMPUTER (PID, CPUTYPE)
VALUES ('P001', 'Intel i9');

-- Sample CART
INSERT INTO CART (CARTID, TOTAL, CID)
VALUES ('CRT01', 1500, 'C001');

-- Sample CART_ENTRY
INSERT INTO CART_ENTRY (CARTID, PID, QUANTITY, PRICE)
VALUES ('CRT01', 'P001', 1, 1500.00);

-- Sample OFFER
INSERT INTO OFFER (PID, PRICE)
VALUES ('P001', 1400.00);

-- Sample TRANSACTION
INSERT INTO TRANSACTIONS (CARTID, CID, SAName, TDATE, CCNUMBER, TTAG)
VALUES ('CRT01', 'C001', 'Home', '2025-05-08', '4111111111111111', 'confirmed');

-- Sample ORDERS
INSERT INTO ORDERS (TID, CID, STATUS, SHIPPING_ADDRESS, PAYMENT_METHOD)
VALUES (1, 'C001', 'CONFIRMED', 'L001', 'CREDIT CARD');


