--run statisitics

SELECT PAYMENT_METHOD,SUM(TOTAL) 
FROM ORDERS,TRANSACTIONS
WHERE CID = 'C001'
GROUP BY PAYMENT_METHOD;

SELECT FNAME,LNAME 
FROM CUSTOMER C JOIN ORDERS O ON CUSTOMERID=O.CID 
GROUP BY CUSTOMERID
ORDER BY SUM(TOTAL) DESC LIMIT 10;


SELECT MAX(PRODUCT_NAME)
FROM (SELECT PRODUCT_NAME, COUNT(PRODUCT_NAME)
          FROM TRANSACTIONS JOIN PRODUCTS ON PRODUCTID=PID 
          WHERE TDATE > 2025-05-08 AND TDATE < 2025-05-14
          GROUP BY PRODUCT_NAME );  



SELECT PRODUCT_NAME
FROM (SELECT PRODUCT_NAME, (COUNT(PRODUCT_NAME)*QUANTITY) AS REAL_TOTAL
          FROM ((CART JOIN CART_ENTRY ON CARTID) JOIN TRANSACTIONS ON CARTID)
          WHERE TDATE > 'start' AND TDATE < 'end-date'
          GROUP BY PRODUCT_NAME )
WHERE REAL_TOTAL = MAX(REAL_TOTAL);


SELECT PAYMENT_TYPE, Max(TOTAL)
FROM (SELECT TRANSACTIONS WHERE TDATE > 'start' AND TDATE < 'end-date')
GROUP BY PAYMENT_TYPE;
 
SELECT PTYPE, AVG(PRICE)
FROM ((SELECT CARTID FROM TRANSACTIONS WHERE TDATE > 'start' AND TDATE < 'end-date')) NATURAL JOIN CARTITEMS JOIN PRODUCTS ON PRODUCTID = PID
GROUP BY PTYPE;





